import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <nav className={styles.nav}>
          {/* <img /> */}
          <Link href="/" passHref>
            {/* <a>Home</a> */}
            <p>Home</p>
          </Link>
          <Link href="/events" passHref>
            {/* <a>Events</a> */}
            <p>Events</p>
          </Link>
          <Link href="/about-us" passHref>
            {/* <a>About us</a> */}
            <p>About us</p>
          </Link>
        </nav>
      </header>

      <main className={`${styles.main} ${inter.className}`}>
        {data.map((ev) => (
          <Link key={ev.id} href={`/events/${ev.id}`} passHref>
            {/* <a href={`/events/${ev.id}`}> */}
              <Image width={300} height={300} src={ev.image} alt={ev.title} />
              <h2>{ev.title}</h2>
              <p>{ev.description}</p>
            {/* </a> */}
          </Link>
        ))}
      </main>
      <footer className={styles.footer}>
        <p>©️2023 NextJS Projects by Eduardo Rocha</p>
      </footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  // const res = await fetch('URL do endpoint da API');  //exemplo de fetch em uma API
  // const data = await res.json(); // exemplo de transformação de dados em JSON
  console.log(events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}
